name: continuous integration

on: [push]

jobs:
  dotnet-publish:

    runs-on: windows-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Unit Test
        run: dotnet test -c Release --logger "trx;logfilename=Tests.trx" --no-restore --verbosity normal --results-directory "TestResults"

      - name: Publish
        run: dotnet publish -c Release --self-contained false --output "Publish"
        
      - name: Publish SC
        run: dotnet publish -c Release --self-contained true --output "PublishSC"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: TestResults
        if: ${{ always() }}
        
      - name: Upload publish results
        uses: actions/upload-artifact@v2
        with:
          name: PopIt.exe
          path: Publish/PopIt.exe

      - name: Upload publish sc results
        uses: actions/upload-artifact@v2
        with:
          name: PopIt-SC.exe
          path: PublishSC/PopIt.exe
